[package]
name = "nate-tests"
version = "0.1.0"
edition = "2018"
authors = ["Ren√© Kijewski <crates.io@k6i.de>"]
license = "Apache-2.0 WITH LLVM-exception"
publish = false

[dependencies]
nate = { path = "../nate", version = "*" }
